"""update phone column

Revision ID: b497be7c89de
Revises: 0384fc1f31b4
Create Date: 2023-08-15 10:36:18.986795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b497be7c89de'
down_revision: Union[str, None] = '0384fc1f31b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.drop_column('users', 'phone_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
